// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.17.3
// source: caked.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Slice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageName          string   `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	Tag                string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Registry           string   `protobuf:"bytes,3,opt,name=registry,proto3" json:"registry,omitempty"`
	PreviousDigest     string   `protobuf:"bytes,4,opt,name=previous_digest,json=previousDigest,proto3" json:"previous_digest,omitempty"`
	PreviousDigestTime int64    `protobuf:"varint,5,opt,name=previous_digest_time,json=previousDigestTime,proto3" json:"previous_digest_time,omitempty"`
	LatestDigest       string   `protobuf:"bytes,6,opt,name=latest_digest,json=latestDigest,proto3" json:"latest_digest,omitempty"`
	LatestDigestTime   int64    `protobuf:"varint,7,opt,name=latest_digest_time,json=latestDigestTime,proto3" json:"latest_digest_time,omitempty"`
	LastChecked        int64    `protobuf:"varint,8,opt,name=last_checked,json=lastChecked,proto3" json:"last_checked,omitempty"`
	LastUpdated        int64    `protobuf:"varint,9,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Architecture       string   `protobuf:"bytes,10,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Os                 string   `protobuf:"bytes,11,opt,name=os,proto3" json:"os,omitempty"`
	ContainerIds       []string `protobuf:"bytes,12,rep,name=container_ids,json=containerIds,proto3" json:"container_ids,omitempty"`
}

func (x *Slice) Reset() {
	*x = Slice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_caked_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slice) ProtoMessage() {}

func (x *Slice) ProtoReflect() protoreflect.Message {
	mi := &file_caked_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slice.ProtoReflect.Descriptor instead.
func (*Slice) Descriptor() ([]byte, []int) {
	return file_caked_proto_rawDescGZIP(), []int{0}
}

func (x *Slice) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *Slice) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Slice) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

func (x *Slice) GetPreviousDigest() string {
	if x != nil {
		return x.PreviousDigest
	}
	return ""
}

func (x *Slice) GetPreviousDigestTime() int64 {
	if x != nil {
		return x.PreviousDigestTime
	}
	return 0
}

func (x *Slice) GetLatestDigest() string {
	if x != nil {
		return x.LatestDigest
	}
	return ""
}

func (x *Slice) GetLatestDigestTime() int64 {
	if x != nil {
		return x.LatestDigestTime
	}
	return 0
}

func (x *Slice) GetLastChecked() int64 {
	if x != nil {
		return x.LastChecked
	}
	return 0
}

func (x *Slice) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

func (x *Slice) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *Slice) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Slice) GetContainerIds() []string {
	if x != nil {
		return x.ContainerIds
	}
	return nil
}

type SliceStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SliceStatus) Reset() {
	*x = SliceStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_caked_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SliceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceStatus) ProtoMessage() {}

func (x *SliceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_caked_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceStatus.ProtoReflect.Descriptor instead.
func (*SliceStatus) Descriptor() ([]byte, []int) {
	return file_caked_proto_rawDescGZIP(), []int{1}
}

func (x *SliceStatus) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SliceStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Image) Reset() {
	*x = Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_caked_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_caked_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_caked_proto_rawDescGZIP(), []int{2}
}

func (x *Image) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_caked_proto protoreflect.FileDescriptor

var file_caked_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x61, 0x6b, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63,
	0x61, 0x6b, 0x65, 0x22, 0xa1, 0x03, 0x0a, 0x05, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x72,
	0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x5f, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x44, 0x69, 0x67,
	0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x14, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x5f,
	0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x12, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x44, 0x69, 0x67, 0x65, 0x73,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x5f,
	0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x61,
	0x74, 0x65, 0x73, 0x74, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x6c, 0x61,
	0x74, 0x65, 0x73, 0x74, 0x5f, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x44, 0x69,
	0x67, 0x65, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74,
	0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x6c, 0x61, 0x73, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6c,
	0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x22,
	0x0a, 0x0c, 0x61, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x6f, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x73, 0x22, 0x3f, 0x0a, 0x0b, 0x53, 0x6c, 0x69, 0x63, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x1b, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x64, 0x0a, 0x05, 0x43, 0x61, 0x6b, 0x65, 0x64, 0x12, 0x2c,
	0x0a, 0x08, 0x52, 0x75, 0x6e, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x12, 0x0b, 0x2e, 0x63, 0x61, 0x6b,
	0x65, 0x2e, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x1a, 0x11, 0x2e, 0x63, 0x61, 0x6b, 0x65, 0x2e, 0x53,
	0x6c, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x09,
	0x53, 0x74, 0x6f, 0x70, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x12, 0x0b, 0x2e, 0x63, 0x61, 0x6b, 0x65,
	0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x1a, 0x11, 0x2e, 0x63, 0x61, 0x6b, 0x65, 0x2e, 0x53, 0x6c,
	0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_caked_proto_rawDescOnce sync.Once
	file_caked_proto_rawDescData = file_caked_proto_rawDesc
)

func file_caked_proto_rawDescGZIP() []byte {
	file_caked_proto_rawDescOnce.Do(func() {
		file_caked_proto_rawDescData = protoimpl.X.CompressGZIP(file_caked_proto_rawDescData)
	})
	return file_caked_proto_rawDescData
}

var file_caked_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_caked_proto_goTypes = []interface{}{
	(*Slice)(nil),       // 0: cake.Slice
	(*SliceStatus)(nil), // 1: cake.SliceStatus
	(*Image)(nil),       // 2: cake.Image
}
var file_caked_proto_depIdxs = []int32{
	0, // 0: cake.Caked.RunSlice:input_type -> cake.Slice
	2, // 1: cake.Caked.StopSlice:input_type -> cake.Image
	1, // 2: cake.Caked.RunSlice:output_type -> cake.SliceStatus
	1, // 3: cake.Caked.StopSlice:output_type -> cake.SliceStatus
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_caked_proto_init() }
func file_caked_proto_init() {
	if File_caked_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_caked_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_caked_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SliceStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_caked_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_caked_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_caked_proto_goTypes,
		DependencyIndexes: file_caked_proto_depIdxs,
		MessageInfos:      file_caked_proto_msgTypes,
	}.Build()
	File_caked_proto = out.File
	file_caked_proto_rawDesc = nil
	file_caked_proto_goTypes = nil
	file_caked_proto_depIdxs = nil
}
