on:
  push:
    branches:
    - main
    - 'release/**'
    - dev
  pull_request:
    branches:
    - main
    - 'release/**'
    - dev

jobs:
  caked:
    env:
      PB_VER: 3.18.0
      GO111MODULE: on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install golang
        run: |
          # Install golang
          wget -nv https://golang.org/dl/go1.17.1.linux-amd64.tar.gz
          rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.17.1.linux-amd64.tar.gz

          # Setting multirun env vars: https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#setting-an-environment-variable
          # $(go env GOPATH) needed so that the protoc plugins can be found
          export PATH="/usr/local/go/bin:$(go env GOPATH)/bin:${PATH}"

          echo "PATH=${PATH}" >> $GITHUB_ENV
      - name: Compile protobuf definitions
        run: |
          # Install protoc - instructions in https://grpc.io/docs/protoc-installation/
          sudo apt-get install -y protobuf-compiler

          # Install protoc plugins
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1

          protoc --go-grpc_out=./caked/pb --go-grpc_opt=paths=source_relative --go_out=./caked/pb --go_opt=paths=source_relative caked.proto
      - name: Test caked
        run: |
          cd ./caked/cmd && go test .
      - name: Build caked
        run: |
          cd ./caked && go build -o caked .
      - name: Ship caked
        run: |
          cd ./caked && echo "Shipping caked, somewhere over the rainbow.."
  cakectl:
    env:
      PB_VER: 3.18.0
      GO111MODULE: on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install golang
        run: |
          # Install golang
          wget -nv https://golang.org/dl/go1.17.1.linux-amd64.tar.gz
          rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.17.1.linux-amd64.tar.gz

          # Setting multirun env vars: https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#setting-an-environment-variable
          # $(go env GOPATH) needed so that the protoc plugins can be found
          export PATH="/usr/local/go/bin:$(go env GOPATH)/bin:${PATH}"

          echo "PATH=${PATH}" >> $GITHUB_ENV
      - name: Compile protobuf definitions
        run: |
          # Install protoc - instructions in https://grpc.io/docs/protoc-installation/
          sudo apt-get install -y protobuf-compiler

          # Install protoc plugins
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1

          protoc --go-grpc_out=./cake/pb --go-grpc_opt=paths=source_relative --go_out=./cake/pb --go_opt=paths=source_relative caked.proto
      - name: Test cakectl
        run: |
          cd ./cake/cmd && go test .
      - name: Build caked
        run: |
          cd ./cake && go build -o cakectl .
      - name: Ship cakectl
        run: |
          cd ./cake && echo "Shipping cakectl, somewhere over the rainbow.."
