on:
  push:
    branches:
    - main
    - 'release/**'
    - dev
  pull_request:
    branches:
    - main
    - 'release/**'
    - dev

# TODO - NEXT: fix workflow
jobs:
  caked:
    env:
      PB_VER: 3.18.0
      GO111MODULE: on
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          mkdir $HOME/.bin

          # Install golang
          wget -nv https://golang.org/dl/go1.17.1.linux-amd64.tar.gz
          tar -C $HOME/.bin -xzf go1.17.1.linux-amd64.tar.gz

          # Install protoc
          curl -LO "https://github.com/protocolbuffers/protobuf/releases/download/v${PB_VER}/protoc-${PB_VER}-linux-x86_64.zip"
          unzip protoc-${PB_VER}-linux-x86_64.zip -d $HOME/.bin
          ls $HOME/.bin/bin

          # Install protoc plugins
          go get google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
      - name: Compile protobuf definitions
        run: |
          export PATH="$PATH:$(go env GOPATH)/bin:$HOME/.bin:$HOME/.bin/go"
          protoc --go-grpc_out=./caked/pb --go-grpc_opt=paths=source_relative --go_out=./caked/pb --go_opt=paths=source_relative caked.proto
      - name: Test caked
        run: |
          cd ./caked/cmd && go test .
      - name: Build caked
        run: |
          cd ./caked && go build . -o caked
      - name: Ship caked
        run: |
          cd ./caked && echo "Shipping caked, somewhere over the rainbow.."
  cake-cli:
    runs-on: ubuntu-latest
    container:
      image: golang:1.17-alpine
    steps:
      - name: Install protobuf compilers
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
      - name: Compile protobuf definitions
        run: |
          export PATH="$PATH:$(go env GOPATH)/bin"
          protoc --go-grpc_out=./cake/pb --go-grpc_opt=paths=source_relative --go_out=./cake/pb --go_opt=paths=source_relative caked.proto
      - name: Build cake-cli
        run: |
          cd ./cake && go build . -o cake
      - name: Ship cake-cli
        run: |
          cd ./cake && echo "Shipping cake, somewhere over the rainbow..
